### ISSUE TITLE
Build: Fix file permission problem in release tests

### ISSUE THREAD

**Issue by smarkwal** [smarkwal/jarhc#107]
When running a release build as part of a GitHub workflow, the following exceptions are thrown:

As part of JUnit tests:
```
java.lang.IllegalArgumentException: File parameter 'file is not writable: '/tmp/junit5758622581481064156/reports/ibm-semeru/17/java-runtime.txt'
	at org.apache.commons.io.FileUtils.requireCanWrite(FileUtils.java:2619)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2447)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3540)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3524)
	at org.jarhc.test.release.utils.TestUtils.normalizeReport(TestUtils.java:50)
	at org.jarhc.test.release.JarHcTest.jarhcTest(JarHcTest.java:306)
	at org.jarhc.test.release.JarHcTest.jarhc_javaRuntime(JarHcTest.java:200)
	at org.jarhc.test.release.JarHcTest.runInContainer(JarHcTest.java:126)
	at org.jarhc.test.release.JarHcTest.lambda$test$3(JarHcTest.java:96)
	at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.lambda$execute$0(DynamicTestTestDescriptor.java:53)
```

During clean-up, most likely due to use of `@TempDir`:
```
java.lang.StackOverflowError
	at java.io.UnixFileSystem.setPermission(Native Method)
	at java.io.File.setReadable(File.java:1624)
	at java.io.File.setReadable(File.java:1658)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.resetPermissions(TempDirectory.java:265)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.access$100(TempDirectory.java:172)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.preVisitDirectory(TempDirectory.java:204)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.preVisitDirectory(TempDirectory.java:199)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.resetPermissionsAndTryToDeleteAgain(TempDirectory.java:247)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:238)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:223)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:199)
	at java.nio.file.Files.walkFileTree(Files.java:2688)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.resetPermissionsAndTryToDeleteAgain(TempDirectory.java:247)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:238)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:223)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:199)
	at java.nio.file.Files.walkFileTree(Files.java:2688)
```

How to investigate:

* Create a new brach.
* Disable all release tests other than the ones on Eclipse Temurin 8.
* Add extra JUnit tests (one running in a Docker container, on running in the hosting JVM) and a Gradle task to log file permissions of /tmp directory.
* Print the current Linux user and group.
* Check the output.

**Comment by smarkwal** [comment]
**Outcome**

The solution has been to get the current user's UID and GID and then use them when starting the Docker containers.

See bb2251f51a162a2a0e26dc02f5772dfe3312485f
